### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by ariefadha** [davwys/arduino-mavlink-sim#4]
Hi thanks for the code.

Can you show me example code using this library to talk to APM/Flight Controller to get the data and send the command?

**Comment by davwys** [comment]
Hi,
This project is not intended for communicating with a Mavlink-based flight controller, but instead with Ground Station applications.
I would suggest looking at the library I used ( https://github.com/alaney/arduino-mavlink ) if you intend to adapt it to send commands and get data from a flight controller.

**Comment by ariefadha** [comment]
and how we get data from MP, i already successfully using your library for sending the data, but i want to know if MP sending new flight mode or new gps data coordinate
